default:
  image: node:24.14.1

stages:
  - build-and-deploy

build-and-deploy-job:
  stage: build-and-deploy
  script:
    - npm install --package-lock-only
    - npm ci
    - npm run build --if-present
    # - npm test
  pages:
    # replace the variable if the Angular app is not named the same way as the git repository
    publish: dist/$CI_PROJECT_NAME/browser
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
